baseURL = "https://danlopez.fyi"
languageCode = "en-us"
title = "danlopez.fyi"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about-me"
    weight = 30

  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing"
    weight = 31

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 40

[permalinks]
  posts = "/:title/"

[outputs]
  home = [ "RSS", "HTML"]
  section  = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]
  [markup.highlight]
    style = "monokailight"
[markup.goldmark.renderer]
    unsafe= true


