# Workflow to build and deploy site to Github Pages using Hugo

# Name of Workflow
name: Deploy site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: self-hosted
    steps:

    - name: Clean public directory
      run: rm -rf public

    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'

    - name: Build
      run: hugo
    
    - name: Copy to site directory
      run: rsync -avz public/* /home/pi/site
